=== byguro/ProcessTestCR/ProcessTestCR/CTest/rules/collocationRules.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

   <xsd:element name="collocationRules">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="collocationRule" minOccurs="0" maxOccurs="unbounded">
               <xsd:complexType>
                  <xsd:sequence>
                     <xsd:element name="constraint" minOccurs="1" maxOccurs="unbounded">
                        <xsd:complexType>
                           <xsd:sequence>
                              <xsd:choice>
                                 <xsd:element ref="token"/>
                                 <xsd:element ref="parse"/>
                              </xsd:choice>
                           </xsd:sequence>
                           <xsd:attribute name="gapAllowedBefore" type="xsd:boolean" default="true"/>
                        </xsd:complexType>
                     </xsd:element>

                     <xsd:element name="action" minOccurs="1" maxOccurs="1" type="unemptyString"/>

                  </xsd:sequence>
               </xsd:complexType>
            </xsd:element>
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>

   <xsd:element name="token">
     <xsd:complexType>
         <xsd:simpleContent>
            <xsd:extension base="unemptyString">
               <xsd:attribute name="matchType" default="string">
                  <xsd:simpleType>
                      <xsd:restriction base="xsd:string">
                         <xsd:enumeration value="string"/>
                         <xsd:enumeration value="regex"/>
                      </xsd:restriction>
                  </xsd:simpleType>
               </xsd:attribute>
            </xsd:extension>
         </xsd:simpleContent>
     </xsd:complexType>
   </xsd:element>
   
   <xsd:element name="parse">
      <xsd:complexType>
          <xsd:simpleContent>
             <xsd:extension base="parseFormat">
                  <xsd:attribute name="matchType" default="rightToLeft">
                  <xsd:simpleType>
                      <xsd:restriction base="xsd:string">
                         <xsd:enumeration value="leftToRight"/>
                         <xsd:enumeration value="rightToLeft"/>
                      </xsd:restriction>
                  </xsd:simpleType>
               </xsd:attribute>
             </xsd:extension>
          </xsd:simpleContent>
      </xsd:complexType>
   </xsd:element>
           
   <xsd:simpleType name="parseFormat">
      <xsd:restriction base="unemptyString">
          <xsd:pattern value='((_[a-zA-Z](=".+")?)|([a-zA-Z0-9çğşıüöÇĞŞIÜÖ]+)|([\-\.\?!/:%])|(\.{3}))((\+[a-zA-Z0-9]+)|\^DB)*(\+\*)?'/>
      </xsd:restriction>
   </xsd:simpleType>
   
   <xsd:simpleType name="unemptyString">
      <xsd:restriction base="xsd:string">
          <xsd:minLength value="1"/>
      </xsd:restriction>
   </xsd:simpleType>
   
</xsd:schema>

=== byguro/ProcessTestCR/ProcessTestCR/CTest/rules/collocationRules.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : collocationRules.xml
    Created on : July 21, 2006, 12:16 PM
    Author     : Turhan O. Daybelge
    Description: This document contains the Collocation Rules that are used by the Collocation Recognizer.
-->

<collocationRules xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='collocationRules.xsd'>
        <collocationRule>   <!--    koşa koşa   //-->
		<constraint gapAllowedBefore="false"><parse matchType="leftToRight">_R+Verb+Pos+Opt+A3sg</parse></constraint>
		<constraint><parse>_R+Verb+Pos+Opt+A3sg</parse></constraint>
		<action>%1 %2+Adverb+ByDoingSo</action>
	</collocationRule>
	<collocationRule>   <!--    duyar duymaz   //-->
		<constraint><parse>_R+Verb+Pos+Aor+A3sg</parse></constraint>
		<constraint><parse>_R+Verb+Neg+Aor+A3sg</parse></constraint>
		<action>%1 %2+Adverb+When</action>
	</collocationRule>
        <collocationRule>   <!--    gitti gideli   //-->
		<constraint><parse>_R+Verb+Pos+Past+A3sg</parse></constraint>
		<constraint><parse>_R+Verb+Pos^DB+Adverb+SinceDoingSo</parse></constraint>
		<action>%1 %2+Adverb+SinceDoingSo</action>
	</collocationRule>
	<collocationRule>   <!--    yapıp yapmama   //-->
		<constraint><parse>_R+Verb+Pos^DB+Adverb+AfterDoingSo</parse></constraint>
		<constraint><parse>_R+Verb+Neg^DB+Noun+Inf2+*</parse></constraint>
		<action>%1 %2+Noun+Inf2+*</action>
	</collocationRule>
        <collocationRule>   <!--    yapsa yapsa   //-->
		<constraint><parse>_R+Verb+Pos+Desr+A3sg</parse></constraint>
		<constraint><parse>_R+Verb+Pos+Desr+A3sg</parse></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    akın akın, kapı kapı   //-->
		<constraint><parse>_R+Noun+Pnon+Nom</parse></constraint>
		<constraint><parse>_R+Noun+Pnon+Nom</parse></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    şırıl şırıl   //-->
		<constraint><parse>_R+Dup</parse></constraint>
		<constraint><parse>_R+Dup</parse></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    güzel güzel   //-->
		<constraint><parse>_R+Adj</parse></constraint>
		<constraint><parse>_R+Adj</parse></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    güzel mi güzel   //-->
		<constraint><parse>_R+Adj</parse></constraint>
                <constraint><parse>_W+Ques</parse></constraint>
		<constraint><parse>_R+Adj</parse></constraint>
		<action>%1 %W %3+Adj</action>
	</collocationRule>
        <collocationRule>   <!--    ev be ev   //-->
		<constraint><parse>_W+Noun+Pnon+Nom</parse></constraint>
                <constraint><token>be</token></constraint>
		<constraint><parse>_W+Noun+Pnon+Nom</parse></constraint>
		<action>%1 %2 %3+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    başlı başına   //-->
                <constraint><token>başlı</token></constraint>
		<constraint><token>başına</token></constraint>
		<action>%1 %2+Adj</action>
	</collocationRule>
        <collocationRule>   <!--    hiç kimse   //-->
                <constraint><token>hiç</token></constraint>
		<constraint><token>kimse</token></constraint>
		<action>%1 %2+Pron</action>
	</collocationRule>
        <collocationRule>   <!--    ne denli   //-->
                <constraint><token>ne</token></constraint>
		<constraint><token>denli</token></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    son derece   //-->
                <constraint><token>son</token></constraint>
                <constraint><token>derece</token></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    şimdiye dek   //-->
                <constraint><token>şimdiye</token></constraint>
                <constraint><token>dek</token></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    okur yazar   //-->
                <constraint><token>okur</token></constraint>
                <constraint><token>yazar</token></constraint>
		<action>%1 %2+Adj</action>
	</collocationRule>
        <collocationRule>   <!--    en azından   //-->
                <constraint><token>en</token></constraint>
		<constraint><token>azından</token></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    hiç olmazsa   //-->
                <constraint><token>hiç</token></constraint>
                <constraint><token>olmazsa</token></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    belli başlı   //-->
                <constraint><token>belli</token></constraint>
                <constraint><token>başlı</token></constraint>
		<action>%1 %2+Adj</action>
	</collocationRule>
        <collocationRule>   <!--    az kalsın   //-->
                <constraint><token>az</token></constraint>
                <constraint><token>kalsın</token></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    can havliyle   //-->
                <constraint><token>can</token></constraint>
                <constraint><token>havliyle</token></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    allaha ısmarladık   //-->
                <constraint><token>allaha</token></constraint>
                <constraint><token>ısmarladık</token></constraint>
		<action>%1 %2+Interj</action>
	</collocationRule>
        <collocationRule>   <!--    tek tük   //-->
                <constraint><token>tek</token></constraint>
                <constraint><token>tük</token></constraint>
		<action>%1 %2+Adj</action>
	</collocationRule>
        <collocationRule>   <!--    her türlü   //-->
                <constraint><token>her</token></constraint>
                <constraint><token>türlü</token></constraint>
		<action>%1 %2+Adj</action>
	</collocationRule>
        <collocationRule>   <!--    öte yandan   //-->
                <constraint><token>öte</token></constraint>
                <constraint><token>yandan</token></constraint>
		<action>%1 %2+Conj</action>
	</collocationRule>
        <collocationRule>   <!--    hem de   //-->
                <constraint><token>hem</token></constraint>
                <constraint><token>de</token></constraint>
		<action>%1 %2+Conj</action>
	</collocationRule>
        <collocationRule>   <!--    ya da   //-->
                <constraint><token>ya</token></constraint>
                <constraint><token>da</token></constraint>
		<action>%1 %2+Conj</action>
	</collocationRule>
        <collocationRule>   <!--    yanı sıra   //-->
                <constraint><token>yanı</token></constraint>
                <constraint><token>sıra</token></constraint>
		<action>%1 %2+Postp+PCGen</action>
	</collocationRule>
        <collocationRule>   <!--    ne menem   //-->
                <constraint><token>ne</token></constraint>
                <constraint><token>menem</token></constraint>
		<action>%1 %2+Adj</action>
	</collocationRule>
        <collocationRule>   <!--    ipe sapa gelmez   //-->
                <constraint><token>ipe</token></constraint>
                <constraint><token>sapa</token></constraint>
                <constraint><token>gelmez</token></constraint>
		<action>%1 %2+Adj</action>
	</collocationRule>
        <collocationRule>   <!--    geçmiş olsuna   //-->
                <constraint><token>geçmiş</token></constraint>
                <constraint><token>olsuna</token></constraint>
		<action>%1 %2+Adverb</action>
	</collocationRule>
        <collocationRule>   <!--    yüzde 12   //-->
                <constraint><token>yüzde</token></constraint>
                <constraint><parse>_R+Num+Card+*</parse></constraint>
		<action>%R+Num+Percent+*</action>
	</collocationRule>
        <collocationRule>   <!--    yüzde 12.2   //-->
                <constraint><token>yüzde</token></constraint>
                <constraint><parse>_R+Num+Real+*</parse></constraint>
		<action>%R+Num+Percent+*</action>
	</collocationRule>
        <collocationRule>   <!--    1000-2000   //-->
                <constraint><parse>_X+Num+Card</parse></constraint>
                <constraint><token>-</token></constraint>
                <constraint><parse>_Y+Num+Card+*</parse></constraint>
		<action>%X-%Y+Num+Range+*</action>
	</collocationRule>

        <collocationRule>   <!--    1000-2000   //-->
                <constraint><parse>_X+Num+Real</parse></constraint>
                <constraint><token>-</token></constraint>
                <constraint><parse>_Y+Num+Card+*</parse></constraint>
		<action>%X-%Y+Num+Range+*</action>
	</collocationRule>

        <collocationRule>   <!--    1000-2000   //-->
                <constraint><parse>_X+Num+Card</parse></constraint>
                <constraint><token>-</token></constraint>
                <constraint><parse>_Y+Num+Real+*</parse></constraint>
		<action>%X-%Y+Num+Range+*</action>
	</collocationRule>

        <collocationRule>   <!--    1000-2000   //-->
                <constraint><parse>_X+Num+Real</parse></constraint>
                <constraint><token>-</token></constraint>
                <constraint><parse>_Y+Num+Real+*</parse></constraint>
		<action>%X-%Y+Num+Range+*</action>
	</collocationRule>

        <collocationRule>   <!--    1000/2000   //-->
                <constraint><parse>_X+Num+Card</parse></constraint>
                <constraint><token>/</token></constraint>
                <constraint><parse>_Y+Num+Card+*</parse></constraint>
		<action>%X/%Y+Num+Ratio+*</action>
	</collocationRule>
        <collocationRule>   <!--    dörtte bir   //-->
                <constraint><parse>_X+Num+Card^DB+Noun+Zero+A3sg+Pnon+Loc</parse></constraint>
                <constraint><parse>_Y+Num+Card+*</parse></constraint>
		<action>%Y/%X+Num+Ratio+*</action>
	</collocationRule>
