=== byguro/ProcessTestCR/ProcessTestCR/CTest/rules/disambiguationRules.xsd
<?xml version="1.0"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

   <xsd:element name="disambiguationRules">
      <xsd:complexType>
         <xsd:sequence>
            <xsd:element name="chooseRule" minOccurs="0" maxOccurs="unbounded" type="ruleType">
                <xsd:unique name="chooseOffset">
                    <xsd:selector xpath="neighbour"/>
                    <xsd:field xpath="@offset"/>
                </xsd:unique>
            </xsd:element>
            <xsd:element name="deleteRule" minOccurs="0" maxOccurs="unbounded" type="ruleType">
                <xsd:unique name="deleteOffset">
                    <xsd:selector xpath="neighbour"/>
                    <xsd:field xpath="@offset"/>
                </xsd:unique>
            </xsd:element>
            
            
         </xsd:sequence>
      </xsd:complexType>
   </xsd:element>
    
    <xsd:complexType name="ruleType">
        <xsd:sequence>
            <xsd:element name="neighbour" minOccurs="0" maxOccurs="unbounded" type="neighbourType"/>
            <xsd:element name="target" minOccurs="1" maxOccurs="1" type="targetType"/>
        </xsd:sequence>
    </xsd:complexType>
                
    <xsd:complexType name="neighbourType">
       <xsd:complexContent>
          <xsd:extension base="neighbourAndTargetType">
             <xsd:attribute name="offset" use="required">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:pattern value="-?[1-9][0-9]*"/>
                    </xsd:restriction>
                </xsd:simpleType>
             </xsd:attribute>
          </xsd:extension>
       </xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="targetType">
        <xsd:complexContent>
            <xsd:extension base="neighbourAndTargetType">
                <xsd:attribute name="offset" type="xsd:integer" fixed="0"/>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>
    
    <xsd:complexType name="neighbourAndTargetType">
      <xsd:complexContent>
         <xsd:extension base="neighbourAndTargetContentsType">
            <xsd:attribute name="firstOfSentence" default="false" type="xsd:boolean"/>
            <xsd:attribute name="lastOfSentence" default="false" type="xsd:boolean"/>
         </xsd:extension>
      </xsd:complexContent>
   </xsd:complexType>
   
   <xsd:complexType name="neighbourAndTargetContentsType">
     <xsd:sequence>
     <xsd:choice>
        <xsd:element ref="token"/>
        <xsd:element ref="parse"/>
     </xsd:choice>
     <xsd:choice minOccurs="0">
        <xsd:element ref="token"/>
        <xsd:element ref="parse"/>
     </xsd:choice>
     </xsd:sequence>
   </xsd:complexType>
   
   <xsd:element name="token">
     <xsd:complexType>
         <xsd:simpleContent>
            <xsd:extension base="unemptyString">
               <xsd:attribute name="matchType" default="string">
                  <xsd:simpleType>
                      <xsd:restriction base="xsd:string">
                         <xsd:enumeration value="string"/>
                         <xsd:enumeration value="regex"/>
                      </xsd:restriction>
                  </xsd:simpleType>
               </xsd:attribute>
            </xsd:extension>
         </xsd:simpleContent>
     </xsd:complexType>
   </xsd:element>
   
   <xsd:element name="parse">
      <xsd:complexType>
          <xsd:simpleContent>
             <xsd:extension base="parseFormat">
                 <xsd:attribute name="stemAllowed" default="true" type="xsd:boolean"/>
             </xsd:extension>
          </xsd:simpleContent>
      </xsd:complexType>
   </xsd:element>
           
   <xsd:simpleType name="parseFormat">
      <xsd:restriction base="unemptyString">
          <xsd:pattern value='((([a-zA-Z0-9çğşıüö]+)|([\-\.\?!/:])|(\.{3})|\^DB)((\+[a-zA-Z0-9]+)|\^DB)*)'/>
      </xsd:restriction>
   </xsd:simpleType>
   
   <xsd:simpleType name="unemptyString">
      <xsd:restriction base="xsd:string">
          <xsd:minLength value="1"/>
      </xsd:restriction>
   </xsd:simpleType>
</xsd:schema>

=== byguro/ProcessTestCR/ProcessTestCR/CTest/rules/disambiguationRules.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : disambiguationRules.xml
    Created on : July 21, 2006, 12:16 PM
    Author     : Turhan O. Daybelge
    Description: This document contains the Disambiguation Rules that are used by the Morphological Disambiguator.
-->

<disambiguationRules xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' xsi:noNamespaceSchemaLocation='disambiguationRules.xsd'>
    <chooseRule>
        <neighbour offset="1"><parse>Conj</parse></neighbour>
        <target><token>ki</token><parse>Conj</parse></target>
    </chooseRule>
    <!--  Rules for handling word "var"  //-->
    <chooseRule>
        <neighbour offset="1"><parse>Punc</parse></neighbour>
        <target><token>var</token><parse>Noun</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="1"><parse>Punc</parse></neighbour>
        <target><token>vardır</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <neighbour offset="1"><parse>Punc</parse></neighbour>
        <target><token>vardı</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>de+Conj</parse></neighbour>
        <neighbour offset="1"><parse>Punc</parse></neighbour>
        <target><token>vardı</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><token>varmış</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><token>varsa</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="1" lastOfSentence="true"><parse>Punc</parse></neighbour>
        <target><token>var</token><parse>Noun</parse></target>
    </chooseRule>
    <!--  Rules for handling word "değil"  //-->
    <chooseRule>
        <neighbour offset="1"><parse>Punc</parse></neighbour>
        <target><token>değil</token><parse>Noun</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="1"><parse>Punc</parse></neighbour>
        <target><token>değildir</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <neighbour offset="1"><parse>Punc</parse></neighbour>
        <target><token>değildi</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>de+Conj</parse></neighbour>
        <neighbour offset="1"><parse>Punc</parse></neighbour>
        <target><token>değildi</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><token>değilmiş</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><token>değilse</token><parse>Noun^DB+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <target firstOfSentence="true"><parse>Conj</parse></target>
    </chooseRule>
    <!--  Rules for handling word "ol"  //-->
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><token>olan</token><parse>Adj</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><token>olmak</token><parse>Noun</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><token>olmuştur</token><parse>Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><token>oldu</token><parse>Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><token>ol</token><parse>Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><parse>ol+Verb^DB+Adj+PresPart</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><parse>ol+Verb^DB+Noun+Inf</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><parse>ol+Verb^DB+Noun+PastPart+Abl</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><parse>ol+Verb^DB+Noun+PastPart+Acc</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><parse>ol+Verb^DB+Noun+FutPart+Abl</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Adj</parse></neighbour>
        <target><parse>ol+Verb^DB+Noun+FutPart+Acc</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><token>olan</token><parse>Adj</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><token>olmak</token><parse>Noun</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><token>olmuştur</token><parse>Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><token>oldu</token><parse>Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><parse>ol+Verb</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><parse>ol+Verb^DB+Adj+PresPart</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Nom</parse></neighbour>
        <target><parse>ol+Verb^DB+Noun+Inf</parse></target>
    </chooseRule>
    <!--  Rules for numeric tokens  //-->
    <chooseRule>
        <neighbour offset="-2"><parse>Num+Card</parse></neighbour>
        <neighbour offset="-1"><parse>Num+Card</parse></neighbour>
        <neighbour offset="1"><parse>Num+Card</parse></neighbour>
        <target><parse>Num+Card</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Num+Card^DB+Noun+Pnon+Loc</parse></neighbour>
        <target><parse>Num+Card^DB+Noun</parse></target>
    </chooseRule>
    <!--  Rules for handling tokens related to date  //-->
    <chooseRule>
        <neighbour offset="-1"><parse>Date</parse></neighbour>
        <target><token>günü</token><parse>Noun+A3sg+P3sg+Nom</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Date</parse></neighbour>
        <target><token>günlü</token><parse>Adj</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Num+Card</parse></neighbour>
        <target><token>yılı</token><parse>Noun+P3sg+Nom</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Num+Card</parse></neighbour>
        <target><token>yılında</token><parse>Noun+P3sg+Loc</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Num+Card</parse></neighbour>
        <target><token>yılından</token><parse>Noun+P3sg+Abl</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Num+Card</parse></neighbour>
        <target><token>yılının</token><parse>Noun+P3sg+Gen</parse></target>
    </chooseRule>
    <!--  Choose the adjectival reading to the verbal reading,   //-->
    <!--  if the next token is a verb  //-->
    <chooseRule>
        <neighbour offset="-1"><parse>Verb+Narr^DB+Adj</parse></neighbour>
        <target><parse>Verb+Pres</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Verb+Narr^DB+Adj</parse></neighbour>
        <target><parse>Verb+Past</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Verb+Narr^DB+Adj</parse></neighbour>
        <target><parse>Verb+Fut</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Verb+Narr^DB+Adj</parse></neighbour>
        <target><parse>Verb+Narr</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Verb+Narr^DB+Adj</parse></neighbour>
        <target><parse>Verb+Neces</parse></target>
    </chooseRule>
    <chooseRule>
        <neighbour offset="-1"><parse>Verb+Narr^DB+Adj</parse></neighbour>
        <target><parse>PastPart</parse></target>
    </chooseRule>
    <!--  Rules for omitting the very infrequent readings for:  //-->
    <!--  For example "ama" is also a noun, and "de" is a verb  //-->
    <chooseRule>
        <target><parse>ama+Conj</parse></target>
    </chooseRule>
    <chooseRule>
        <target><parse>de+Conj</parse></target>
    </chooseRule>
    <chooseRule>
        <target><parse>ya+Conj</parse></target>
    </chooseRule>
    <chooseRule>
        <target><parse>hatta+Conj</parse></target>
    </chooseRule>
    <chooseRule>
        <target><token>aslında</token><parse>Adverb</parse></target>
    </chooseRule>
    <chooseRule>
        <target><token>artık</token><parse>Adverb</parse></target>
    </chooseRule>
    <chooseRule>
        <target><token>yalnız</token><parse>Adverb</parse></target>
    </chooseRule>
    <chooseRule>
        <target><token>öylesine</token><parse>Adverb</parse></target>
    </chooseRule>
    <chooseRule>
        <target><parse>diye+Postp+PCNom</parse></target>
    </chooseRule>
    <chooseRule>
        <target><token>hala</token><parse>Adverb</parse></target>
    </chooseRule>
    <chooseRule>
